services:
  node:
    container_name: node
    image: "hyperledger/besu:latest"
    ports:
      - "127.0.0.1:30303:30303/udp"
      - "127.0.0.1:30303:30303/tcp"
      - "127.0.0.1:8545:8545/udp"
      - "127.0.0.1:8545:8545/tcp"
    expose: ["8545", "30303"]
    volumes:
      - type: bind
        source: ./data/genesis.json
        target: /opt/besu/genesis.json
        read_only: true
      - type: bind
        source: ./configs/node.toml
        target: /opt/besu/configs/node.toml
        read_only: true
      - type: bind
        source: ./data/keys
        target: /opt/besu/keys
        read_only: true
    command:
      - "--config-file=configs/node.toml"

    entrypoint:
      - "besu"