services:
  genesis-generator:
    container_name: genesis-generator
    image: "hyperledger/besu:latest"
    volumes:
      - type: bind
        source: ./data
        target: /opt/besu/data
        read_only: false
      - type: bind
        source: ./configs
        target: /opt/besu/configs
        read_only: true
    command: [ "operator", "generate-blockchain-config", "--config-file=configs/networkConfig.json", "--to=data", "--private-key-file-name=key" ]
    entrypoint:
      - "besu"
  node:
    container_name: node
    image: "hyperledger/besu:latest"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "30303:30303/udp"
      - "30303:30303/tcp"
      - "127.0.0.1:8545:8545"
      - "127.0.0.1:8551:8551"
      - "127.0.0.1:8086:8086"
    expose: ["8545", "8551"]
    command: [ "--config-file=configs/node.toml" ]
    entrypoint:
      - "besu"

